name       : dump_syms
version    : 2.1.1
release    : 5
source     :
    - https://github.com/mozilla/dump_syms/archive/refs/tags/v2.1.1.tar.gz : 5b7b4f8fdd15045605062d246c0d7b8002d806ada609c76527f8c8df2bce56b9
homepage   : https://github.com/mozilla/dump_syms
license    :
    - Apache
    - MIT
component  : programming.tools
summary    : Rewrite of breakpad dump_syms tools in Rust
description: |
    dump_syms is a command-line utility for parsing the debugging information the compiler provides (whether as DWARF or STABS sections in an ELF file or as stand-alone PDB files) and writing that information back out in the Breakpad symbol file format.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release
install    : |
    install -Dm00755 target/release/dump_syms $installdir/usr/bin/dump_syms
