name       : dump_syms
version    : 2.0.0
release    : 4
source     :
    - https://github.com/mozilla/dump_syms/archive/refs/tags/v2.0.0.tar.gz : 36b74696c40232d03404e95e6aadadebe4645d03b51bf575f0671b341c14f1ad
license    :
    - Apache
    - MIT
component  : programming.tools
summary    : dump_syms is a command-line utility for parsing the debugging information the compiler provides (whether as DWARF or STABS sections in an ELF file or as stand-alone PDB files) and writing that
    information back out in the Breakpad symbol file format.
description: |
    dump_syms is a command-line utility for parsing the debugging information the compiler provides (whether as DWARF or STABS sections in an ELF file or as stand-alone PDB files) and writing that information back out in the Breakpad symbol file format.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release
install    : |
    install -Dm00755 target/release/dump_syms $installdir/usr/bin/dump_syms
