name       : dump_syms
version    : 2.2.1
release    : 6
source     :
    - https://github.com/mozilla/dump_syms/archive/refs/tags/v2.2.1.tar.gz : 54a37468a9936f6b18644da2cb296b55869236507a238c30d055190091a09c44
homepage   : https://github.com/mozilla/dump_syms
license    :
    - Apache
    - MIT
component  : programming.tools
summary    : Rewrite of breakpad dump_syms tools in Rust
description: |
    dump_syms is a command-line utility for parsing the debugging information the compiler provides (whether as DWARF or STABS sections in an ELF file or as stand-alone PDB files) and writing that information back out in the Breakpad symbol file format.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release
install    : |
    install -Dm00755 target/release/dump_syms $installdir/usr/bin/dump_syms
